export const SET_PROFILE = 'SET_PROFILE'
export const SET_CURRENT_PROFILE_ID = 'SET_CURRENT_PROFILE_ID'
export const SET_PROFILE_STATUS = 'SET_PROFILE_STATUS'
export const ADD_POST = 'ADD_POST'
export const UPDATE_NEW_POST = 'UPDATE_NEW_POST'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_NEW_MESSAGE = 'UPDATE_NEW_MESSAGE'

export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const SET_USERS = 'SET_USERS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TOTAL_USER_COUNT = 'SET_TOTAL_USER_COUNT'
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const TOGGLE_FOLLOWING_IN_PROGRESS = 'TOGGLE_FOLLOWING_IN_PROGRESS'

export const SET_AUTH_DATA = 'SET_AUTH_DATA'
