export const SET_IS_INITIALIZED = 'SET_IS_INITIALIZED'
export const SET_NEW_MESSAGE_COUNT = 'SET_NEW_MESSAGE_COUNT'

export const SET_PROFILE = 'SET_PROFILE'
export const SET_CURRENT_PROFILE_ID = 'SET_CURRENT_PROFILE_ID'
export const SET_PROFILE_STATUS = 'SET_PROFILE_STATUS'
export const ADD_POST = 'ADD_POST'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const SET_DIALOGS = 'SET_DIALOGS'
export const SET_CURRENT_DIALOG_ID = 'SET_CURRENT_DIALOG_ID'
export const SET_CURRENT_DIALOG_PHOTO = 'SET_CURRENT_DIALOG_PHOTO'
export const TOGGLE_MESSAGES_FETCHING = 'TOGGLE_MESSAGES_FETCHING'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'


export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const SET_USERS = 'SET_USERS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TOTAL_USER_COUNT = 'SET_TOTAL_USER_COUNT'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const TOGGLE_FOLLOWING_IN_PROGRESS = 'TOGGLE_FOLLOWING_IN_PROGRESS'

export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_USER_DATA = 'SET_USER_DATA'
